### PR TITLE
Fix `aga_product` in `test_cases` and more 

### PR DESCRIPTION
**Pull request by FlickerSoul**
* Fix `aga_product` in `test_cases`
* support singleton input for `aga_*` kwargs, like `aga_hidden=True`
* add more tests

### CODE REVIEW

**Comment by FlickerSoul** [comment]
sorry about the messy naming scheme. I'll refactor it a bit later :)

**Comment by FlickerSoul** [comment]
and probably making things too complicated than it should be. removing some of the support like you said can be a better idea :)

**Comment by nihilistkitten** [comment]
To be honest, I think overload is not the right solution. I think we can just break backwards compatibility; there's really no reason to support giving iterators as options to `test_cases`. Thoughts?

**Comment by nihilistkitten** [comment]
To be honest, I think overload is not the right solution. I think we can just break backwards compatibility; there's really no reason to support giving iterators as options to `test_cases`. Thoughts?

Also a few linter errors - I don't really care about the line break before binary operator, you can disable that in `.flake8` if you want (add "W503" to ignore) since it's [being deprecated](https://www.flake8rules.com/rules/W503.html) anyway, but if you can fix the line length error it'd be awesome.

Thanks!

**Comment by FlickerSoul** [comment]
I'll fix the linter errors :)

**Pull request merged**
